DROP TABLE IF EXISTS EMPLOYEE;  
CREATE TABLE EMPLOYEE (  
EMPL_ID INT AUTO_INCREMENT  PRIMARY KEY,  
EMP_NAME VARCHAR(50) NOT NULL,  
EMP_DESIGNATION VARCHAR(8) NOT NULL,  
EMP_EMAIL VARCHAR(50) NOT NULL
);  